### PR TITLE
Fixing all goroutine leaks with client closings

### LINKED ISSUE #1035: Bug: leaking goroutines
**Describe the bug**
gnomock is leaking goroutines.

**To Reproduce**
Add this code to kafka test (and do `go mod tidy`). This checks for any running goroutines at the end of the test.

(It's possibly in other tests too, I just use this package for kafka.)

```

import (
	"go.uber.org/goleak"
)
func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}
```

You will see many HTTP read/write loops still running around.

**Expected behavior**

No running goroutines after the end of the test

**System (please complete the following information):**
 - OS: macOS
 - Version: 14.4.1
 - Docker version: 25.0.3 (but I don't think that relates to anything)

**Additional context**
I am using goleak to detect "forgotten" goroutines in my code. I now cannot, because gnomock's own goroutines are still running around somewhere.

I suspect some clients have keep alives turned on, and CloseIdleConnections was not called on them. I will try to dig more and make a PR.

### PR DESCRIPTION
**Pull request by karelbilek**
Also adds uber's goroutine leaks checker to almost all tests.

The biggest change here is adding context to sidecar pull, which is then cancelled if the container creation fails. This prevents the sidecar goroutine from leaking. The same for making the sidecar channel buffered; the goroutine is not stuck when nobody reads from it. (It is not a memory leak either, GC will remove the channel.)

Other changes are just annoying work; putting client.Close() everywhere, db.Close() when Ping() is not successful, client closes in tests/presets, etc.

internal/gnomockd/ tests still show goroutine leaks for http transport, but I have no idea what is gnomockd even doing, let alone the tests, so I let that be.

Fixes #1035

### CODE REVIEW

**Comment by karelbilek** [comment]
note that this and #1042 are in "conflict"; one will need to be rebased after the other is merged

File: preset/cockroachdb/preset.go [hunk 1]
```diff
@@ -87,6 +87,10 @@ func (p *P) setDefaults() {
 func healthcheck(_ context.Context, c *gnomock.Container) error {
 	db, err := connect(c, "")
 	if err != nil {
+		if db != nil {
+			db.Close()
```
Comment (orlangure) [inline preset/cockroachdb/preset.go:91]:
```suggestion
			_ = db.Close()
```

File: preset/mariadb/preset.go [hunk 2]
```diff
@@ -91,6 +91,10 @@ func (p *P) healthcheck(_ context.Context, c *gnomock.Container) error {
 
 	db, err := p.connect(addr)
 	if err != nil {
+		if db != nil {
+			db.Close()
```
Comment (orlangure) [inline preset/mariadb/preset.go:95]:
```suggestion
			_ = db.Close()
```

File: preset/mysql/preset.go [hunk 3]
```diff
@@ -93,6 +93,10 @@ func (p *P) healthcheck(_ context.Context, c *gnomock.Container) error {
 
 	db, err := p.connect(addr)
 	if err != nil {
+		if db != nil {
+			db.Close()
```
Comment (orlangure) [inline preset/mysql/preset.go:97]:
```suggestion
			_ = db.Close()
```

File: preset/postgres/preset.go [hunk 4]
```diff
@@ -93,6 +93,10 @@ func (p *P) Options() []gnomock.Option {
 func (p *P) healthcheck(_ context.Context, c *gnomock.Container) error {
 	db, err := connect(c, defaultDatabase)
 	if err != nil {
+		if db != nil {
+			db.Close()
```
Comment (orlangure) [inline preset/postgres/preset.go:97]:
```suggestion
			_ = db.Close()
```

**Review by orlangure — DISMISSED** [review]
Nice, I learned something new today - I wanted to try `goleak` for a while 😼 
There are a couple of small changes to make ignored errors explicit. Please apply these suggestions when you rebase and resolve conflicts (and if you see similar cases in other changes - please handle these as well)

Amazing work, thank you!

**Comment by karelbilek** [comment]
I will wait for the lint fix to be merged as that will basically show this
up :)

**Comment by orlangure** [comment]
Linter PR is merged 😼

**Comment by karelbilek** [comment]
No idea what to do with the code coverage stuff so I ignore it?

**Review by orlangure — APPROVED** [review]
Thank you 😼 

Yeah, codecov can be ignored for now. We send coverage reports from every test job, and at some point they made a change that first stopped all deliveries (I think my token was suspended? Not sure), and after that upload attempts started getting throttled with heavy rate limits.

I will hopefully get to this at some point and figure out what's wrong with the token, and maybe I'll have to look for another coverage provider, free for open source.
